services:
  drone-vc-p:
    build: .
    environment:
      API_ID: $API_ID  
      API_HASH: $API_HASH  
      BOT_TOKEN: $BOT_TOKEN 
      OWNER_ID: $OWNER_ID
      DRIVE_FOLDER_ID: $DRIVE_FOLDER_ID
      DOWNLOAD_DIR: $DOWNLOAD_DIR
    resources:
      cpu: 1000m
      memory: 3Gi
